### ISSUE TITLE
Ne pas verser les modules nodes dans le repo

### ISSUE THREAD

**Issue by emchateau** [publicarchi/prosopo#6]
Salut Lena,

Je viens de recevoir une alerte de sécurité de GitHub concernant ce repo. C’est sans doute lié au fait qu’il contient une tonne de modules nodeJS.

C’est une mauvaise pratique que de verser du code dont on n’est pas l’auteur dans un repo. Pour une application node on utilise généralement un fichier de config avec un outil de déploiement pour installer les modules nécessaires, mais ceux-ci ne doivent pas figurer dans l’historique du répertoire. Sinon, on utilise des sous-modules git.

L’idée est d’éviter d’avoir un historique chargé de code inutile et d’autre part de pouvoir faire les mises à jour lorsque nécessaire.

La prochaine fois que l’on travaille ensemble, je vais réinstaller le repo et on règlera ces détails. On peut aussi utiliser une branche.

Amitiés,
Emmanuel

**Comment by lenaMK** [comment]
Salut,

Mince désolée je n'avais pas réalisé que ce serait ce qui arriverait. 

À ce sujet, quand voudrais-tu travailler ensemble cette semaine? Je ferai de la transcription et un peu de recherche d'ici là.

**Comment by lenaMK** [comment]
Salut, J'ai créé un branche locale et j'ai fait le gitignore sure le dossier node_modules. Je peux faire un pull request ou sinon juste attendre qu'on le fasse ensemble.

**Comment by emchateau** [comment]
Salut,
Vu que tout le bazard est dans l’historique, il faut que je supprime cette partie de l’historique.
Cet après-midi ?
Emmanuel

Emmanuel Château-Dutier

2906, avenue de Soissons
H3S 1V9 Montréal, Québec, Canada
+1 438 502 2424 | @emchateau

**Comment by lenaMK** [comment]
C'est bon pour moi
